version: "3.7"
services:
  backend:
    image: parseplatform/parse-server:4.5.0
    environment:
      PARSE_SERVER_APPLICATION_ID: geotag
      PARSE_SERVER_MASTER_KEY: ${MASTER_KEY}
      PARSE_SERVER_DATABASE_URI: mongodb://mongodb/geotag
    ports:
      - "127.0.0.1:1337:1337"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  nginx:
    image: nginx:1.21.0-alpine
    volumes:
      - "./front:/usr/share/nginx/html"
    ports:
      - "127.0.0.1:8080:80"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  dashboard:
    image: parseplatform/parse-dashboard
    environment: # https://hub.docker.com/r/parseplatform/parse-dashboard
      PARSE_DASHBOARD_SERVER_URL: ${BACKEND_URL}/parse
      PARSE_DASHBOARD_APP_ID: geotag
      PARSE_DASHBOARD_MASTER_KEY: ${MASTER_KEY}
      PARSE_DASHBOARD_USER_ID: ${USER_NAME}
      PARSE_DASHBOARD_USER_PASSWORD: ${USER_PASSWORD}
      PARSE_DASHBOARD_ALLOW_INSECURE_HTTP: 1
    ports:
      - "127.0.0.1:4040:4040"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  mongodb:
    image: mongo:4.4
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
